#!/usr/bin/bash

#SBATCH --job-name=pii-state-ml
#SBATCH --output=slurm_output/%A_%4a.out
#SBATCH --error=slurm_output/%A_%4a.err
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH --array=0-0

echo "[JOB] Running job on ${SLURMD_NODENAME}"

# Check for first argument
if [ -z "$1" ]
  then
    echo "Missing required argument 1: configuration file"
    exit 1
fi

REPO_DIR=$(pwd)
cd matrix_models

# Create TMP directory
mkdir -p /home/reujpasternak/tmp
export TMPDIR=/home/reujpasternak/tmp/

# Obtain the current location
HDIR=$(pwd)

# Specify configuration file
CONFIG_FILE=${1}
echo "[JOB] Using configuration file ${1}"

# List directory names
CONFIG_DIR=transformer_configs
INPUT_DIR=matrix_data
SAVED_MODELS_DIR=saved_transformer_models
PLOT_DIR=transformer_matrix_plot_data
PLOT_DATA_DIR=transformer_matrix_plots

# Create a temporary working directory on the node
WDIR=/home/reujpasternak/tmp/pii-state-ml
mkdir -p ${WDIR}

# Tidy up prior job files, except the virtual environment
ls ${WDIR} | grep -xvF torch_venv | xargs rm -rf --

# Create subdirectories within working directory
mkdir -p ${WDIR}/${CONFIG_DIR}
mkdir -p ${WDIR}/${INPUT_DIR}
mkdir -p ${WDIR}/${SAVED_MODELS_DIR}
mkdir -p ${WDIR}/${PLOT_DIR}
mkdir -p ${WDIR}/${PLOT_DATA_DIR}
cd ${WDIR}

# Copy set of input files to the working directory
echo "[JOB] Copying input files to working directory..."
cp    ${HDIR}/${CONFIG_DIR}/*.json     ${WDIR}/${CONFIG_DIR}
cp    ${HDIR}/${INPUT_DIR}/*.csv.gz    ${WDIR}/${INPUT_DIR}
cp -a ${HDIR}/${SAVED_MODELS_DIR}/*    ${WDIR}/${SAVED_MODELS_DIR}

# Unzip input data
echo "[JOB] Unzipping input data..."
gunzip -v ${WDIR}/${INPUT_DIR}/*.csv.gz

# Setup PyTorch environment and run
echo "[JOB] Creating PyTorch virtual environment..."

export PYTHONOPTIMIZE=2 # Disable assertions and docstrings
python3 -m venv ${WDIR}/torch_venv
source ${WDIR}/torch_venv/bin/activate

python3 -m pip install torch torchvision --index-url https://download.pytorch.org/whl/cu129
python3 -m pip install -r ${REPO_DIR}/requirements.txt

echo "[JOB] About to run python script"
python3 -u ${HDIR}/transformer_matrix.py ${CONFIG_DIR}/${CONFIG_FILE}

# Copy the set of output files back to the original folder
echo "[JOB] Copying output files back to home directory..."
cp -a ${WDIR}/${PLOT_DIR}/*         ${HDIR}/${PLOT_DIR}/
cp -a ${WDIR}/${PLOT_DATA_DIR}/*    ${HDIR}/${PLOT_DATA_DIR}/
cp -a ${WDIR}/${SAVED_MODELS_DIR}/* ${HDIR}/${SAVED_MODELS_DIR}/

echo "[JOB] Cleaning up local files"
# Tidy up local files, except the virtual environment (save for future use)
ls ${WDIR} | grep -xvF torch_venv | xargs rm -rf --

echo "[JOB] Job ${SLURM_JOB_ID} complete!"

# TRIAL_SIZE=1000
# N_SIZES=(20 30 40 50 60 70 80 90 100)
# N_PROGRAMS=10

# N_INDEX=$(($SLURM_ARRAY_TASK_ID / $N_PROGRAMS))
# N_SIZE=${N_SIZES[$N_INDEX]}

# PROGRAM_ID=$(($SLURM_ARRAY_TASK_ID % $N_PROGRAMS))

# java Main $TRIAL_SIZE $N_SIZE data/stateData_2000_${N_SIZE}_ID${PROGRAM_ID}.csv $PROGRAM_ID