#!/usr/bin/bash

PARTITION="hslinux"

# If arg 1 is not empty, then use it as the partition
if [ ! -z "$1" ]
  then
    PARTITION=${1}
fi

# If arg 2 is not empty, then use it as the node list
if [ ! -z "$2" ]
  then
    NODE_LIST_ARG="--nodelist ${2}"
else
    NODE_LIST_ARG=""
fi

JOB_OUTPUT=$(sbatch --partition ${PARTITION} ${NODE_LIST_ARG} job)
echo $JOB_OUTPUT

# TODO: Watch the output in slurm_output instead of (or after) the job status

# Send job ID to monitor script
bash monitor $(echo $JOB_OUTPUT | grep -E -o -a -m 1 -h "[0-9]+")