#!/usr/bin/bash

if [ -z "$1" ]
  then
    echo "Missing required argument 1: configuration file"
    exit 1
fi

CONFIG_FILE=${1}

PARTITION="hslinux"
# If arg 2 is not empty, then use it as the partition
if [ ! -z "$2" ]
  then
    PARTITION=${2}
fi

# If arg 3 is not empty, then use it as the node list
if [ ! -z "$3" ]
  then
    NODE_LIST_ARG="--nodelist ${3}"
else
    NODE_LIST_ARG=""
fi

JOB_OUTPUT=$(sbatch --partition ${PARTITION} ${NODE_LIST_ARG} job ${CONFIG_FILE})
echo $JOB_OUTPUT

# TODO: Watch the output in slurm_output instead of (or after) the job status

# Send job ID to monitor script
JOB_ID=$(echo $JOB_OUTPUT | grep -E -o -a -m 1 -h "[0-9]+")
bash monitor $JOB_ID
watch -n 2 "tail -n 20 slurm_output/${JOB_ID}_0000.out"